// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: org/apache/tika/grpc/v2/document.proto

// Protobuf Java Version: 3.25.8
package org.apache.tika.grpc.v2;

public interface DocumentMetadataOrBuilder extends
    // @@protoc_insertion_point(interface_extends:org.apache.tika.grpc.v2.DocumentMetadata)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string title = 1;</code>
   * @return The title.
   */
  java.lang.String getTitle();
  /**
   * <code>string title = 1;</code>
   * @return The bytes for title.
   */
  com.google.protobuf.ByteString
      getTitleBytes();

  /**
   * <code>repeated string authors = 2;</code>
   * @return A list containing the authors.
   */
  java.util.List<java.lang.String>
      getAuthorsList();
  /**
   * <code>repeated string authors = 2;</code>
   * @return The count of authors.
   */
  int getAuthorsCount();
  /**
   * <code>repeated string authors = 2;</code>
   * @param index The index of the element to return.
   * @return The authors at the given index.
   */
  java.lang.String getAuthors(int index);
  /**
   * <code>repeated string authors = 2;</code>
   * @param index The index of the value to return.
   * @return The bytes of the authors at the given index.
   */
  com.google.protobuf.ByteString
      getAuthorsBytes(int index);

  /**
   * <code>string description = 3;</code>
   * @return The description.
   */
  java.lang.String getDescription();
  /**
   * <code>string description = 3;</code>
   * @return The bytes for description.
   */
  com.google.protobuf.ByteString
      getDescriptionBytes();

  /**
   * <code>repeated string keywords = 4;</code>
   * @return A list containing the keywords.
   */
  java.util.List<java.lang.String>
      getKeywordsList();
  /**
   * <code>repeated string keywords = 4;</code>
   * @return The count of keywords.
   */
  int getKeywordsCount();
  /**
   * <code>repeated string keywords = 4;</code>
   * @param index The index of the element to return.
   * @return The keywords at the given index.
   */
  java.lang.String getKeywords(int index);
  /**
   * <code>repeated string keywords = 4;</code>
   * @param index The index of the value to return.
   * @return The bytes of the keywords at the given index.
   */
  com.google.protobuf.ByteString
      getKeywordsBytes(int index);

  /**
   * <code>repeated string languages = 5;</code>
   * @return A list containing the languages.
   */
  java.util.List<java.lang.String>
      getLanguagesList();
  /**
   * <code>repeated string languages = 5;</code>
   * @return The count of languages.
   */
  int getLanguagesCount();
  /**
   * <code>repeated string languages = 5;</code>
   * @param index The index of the element to return.
   * @return The languages at the given index.
   */
  java.lang.String getLanguages(int index);
  /**
   * <code>repeated string languages = 5;</code>
   * @param index The index of the value to return.
   * @return The bytes of the languages at the given index.
   */
  com.google.protobuf.ByteString
      getLanguagesBytes(int index);

  /**
   * <code>repeated string publishers = 6;</code>
   * @return A list containing the publishers.
   */
  java.util.List<java.lang.String>
      getPublishersList();
  /**
   * <code>repeated string publishers = 6;</code>
   * @return The count of publishers.
   */
  int getPublishersCount();
  /**
   * <code>repeated string publishers = 6;</code>
   * @param index The index of the element to return.
   * @return The publishers at the given index.
   */
  java.lang.String getPublishers(int index);
  /**
   * <code>repeated string publishers = 6;</code>
   * @param index The index of the value to return.
   * @return The bytes of the publishers at the given index.
   */
  com.google.protobuf.ByteString
      getPublishersBytes(int index);

  /**
   * <pre>
   * Unambiguous references to the resource as declared by the document itself
   * (DOI, ISBN, ...), from dc:identifier.
   * </pre>
   *
   * <code>repeated string identifiers = 7;</code>
   * @return A list containing the identifiers.
   */
  java.util.List<java.lang.String>
      getIdentifiersList();
  /**
   * <pre>
   * Unambiguous references to the resource as declared by the document itself
   * (DOI, ISBN, ...), from dc:identifier.
   * </pre>
   *
   * <code>repeated string identifiers = 7;</code>
   * @return The count of identifiers.
   */
  int getIdentifiersCount();
  /**
   * <pre>
   * Unambiguous references to the resource as declared by the document itself
   * (DOI, ISBN, ...), from dc:identifier.
   * </pre>
   *
   * <code>repeated string identifiers = 7;</code>
   * @param index The index of the element to return.
   * @return The identifiers at the given index.
   */
  java.lang.String getIdentifiers(int index);
  /**
   * <pre>
   * Unambiguous references to the resource as declared by the document itself
   * (DOI, ISBN, ...), from dc:identifier.
   * </pre>
   *
   * <code>repeated string identifiers = 7;</code>
   * @param index The index of the value to return.
   * @return The bytes of the identifiers at the given index.
   */
  com.google.protobuf.ByteString
      getIdentifiersBytes(int index);

  /**
   * <code>.google.protobuf.Timestamp created = 10;</code>
   * @return Whether the created field is set.
   */
  boolean hasCreated();
  /**
   * <code>.google.protobuf.Timestamp created = 10;</code>
   * @return The created.
   */
  com.google.protobuf.Timestamp getCreated();
  /**
   * <code>.google.protobuf.Timestamp created = 10;</code>
   */
  com.google.protobuf.TimestampOrBuilder getCreatedOrBuilder();

  /**
   * <code>.google.protobuf.Timestamp modified = 11;</code>
   * @return Whether the modified field is set.
   */
  boolean hasModified();
  /**
   * <code>.google.protobuf.Timestamp modified = 11;</code>
   * @return The modified.
   */
  com.google.protobuf.Timestamp getModified();
  /**
   * <code>.google.protobuf.Timestamp modified = 11;</code>
   */
  com.google.protobuf.TimestampOrBuilder getModifiedOrBuilder();

  /**
   * <pre>
   * free-text rights/license statement, from dc:rights
   * </pre>
   *
   * <code>string rights = 20;</code>
   * @return The rights.
   */
  java.lang.String getRights();
  /**
   * <pre>
   * free-text rights/license statement, from dc:rights
   * </pre>
   *
   * <code>string rights = 20;</code>
   * @return The bytes for rights.
   */
  com.google.protobuf.ByteString
      getRightsBytes();
}
