// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: org/apache/tika/grpc/v2/tika_v2.proto

// Protobuf Java Version: 3.25.8
package org.apache.tika.grpc.v2;

/**
 * Protobuf type {@code org.apache.tika.grpc.v2.FetchAndParseRequest}
 */
public final class FetchAndParseRequest extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:org.apache.tika.grpc.v2.FetchAndParseRequest)
    FetchAndParseRequestOrBuilder {
private static final long serialVersionUID = 0L;
  // Use FetchAndParseRequest.newBuilder() to construct.
  private FetchAndParseRequest(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private FetchAndParseRequest() {
    fetcherId_ = "";
    fetchKey_ = "";
    additionalFetchConfigJson_ = "";
    emitterId_ = "";
    parseContextJson_ = "";
  }

  @java.lang.Override
  @SuppressWarnings({"unused"})
  protected java.lang.Object newInstance(
      UnusedPrivateParameter unused) {
    return new FetchAndParseRequest();
  }

  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return org.apache.tika.grpc.v2.TikaV2Proto.internal_static_org_apache_tika_grpc_v2_FetchAndParseRequest_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return org.apache.tika.grpc.v2.TikaV2Proto.internal_static_org_apache_tika_grpc_v2_FetchAndParseRequest_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            org.apache.tika.grpc.v2.FetchAndParseRequest.class, org.apache.tika.grpc.v2.FetchAndParseRequest.Builder.class);
  }

  public static final int FETCHER_ID_FIELD_NUMBER = 1;
  @SuppressWarnings("serial")
  private volatile java.lang.Object fetcherId_ = "";
  /**
   * <pre>
   * ID of a fetcher previously saved through the v1 Tika service.
   * </pre>
   *
   * <code>string fetcher_id = 1;</code>
   * @return The fetcherId.
   */
  @java.lang.Override
  public java.lang.String getFetcherId() {
    java.lang.Object ref = fetcherId_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      fetcherId_ = s;
      return s;
    }
  }
  /**
   * <pre>
   * ID of a fetcher previously saved through the v1 Tika service.
   * </pre>
   *
   * <code>string fetcher_id = 1;</code>
   * @return The bytes for fetcherId.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getFetcherIdBytes() {
    java.lang.Object ref = fetcherId_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      fetcherId_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int FETCH_KEY_FIELD_NUMBER = 2;
  @SuppressWarnings("serial")
  private volatile java.lang.Object fetchKey_ = "";
  /**
   * <code>string fetch_key = 2;</code>
   * @return The fetchKey.
   */
  @java.lang.Override
  public java.lang.String getFetchKey() {
    java.lang.Object ref = fetchKey_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      fetchKey_ = s;
      return s;
    }
  }
  /**
   * <code>string fetch_key = 2;</code>
   * @return The bytes for fetchKey.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getFetchKeyBytes() {
    java.lang.Object ref = fetchKey_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      fetchKey_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int ADDITIONAL_FETCH_CONFIG_JSON_FIELD_NUMBER = 3;
  @SuppressWarnings("serial")
  private volatile java.lang.Object additionalFetchConfigJson_ = "";
  /**
   * <code>string additional_fetch_config_json = 3;</code>
   * @return The additionalFetchConfigJson.
   */
  @java.lang.Override
  public java.lang.String getAdditionalFetchConfigJson() {
    java.lang.Object ref = additionalFetchConfigJson_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      additionalFetchConfigJson_ = s;
      return s;
    }
  }
  /**
   * <code>string additional_fetch_config_json = 3;</code>
   * @return The bytes for additionalFetchConfigJson.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getAdditionalFetchConfigJsonBytes() {
    java.lang.Object ref = additionalFetchConfigJson_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      additionalFetchConfigJson_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int EMITTER_ID_FIELD_NUMBER = 4;
  @SuppressWarnings("serial")
  private volatile java.lang.Object emitterId_ = "";
  /**
   * <code>string emitter_id = 4;</code>
   * @return The emitterId.
   */
  @java.lang.Override
  public java.lang.String getEmitterId() {
    java.lang.Object ref = emitterId_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      emitterId_ = s;
      return s;
    }
  }
  /**
   * <code>string emitter_id = 4;</code>
   * @return The bytes for emitterId.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getEmitterIdBytes() {
    java.lang.Object ref = emitterId_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      emitterId_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int PARSE_CONTEXT_JSON_FIELD_NUMBER = 5;
  @SuppressWarnings("serial")
  private volatile java.lang.Object parseContextJson_ = "";
  /**
   * <pre>
   * Optional JSON object to configure the ParseContext for this request.
   * </pre>
   *
   * <code>string parse_context_json = 5;</code>
   * @return The parseContextJson.
   */
  @java.lang.Override
  public java.lang.String getParseContextJson() {
    java.lang.Object ref = parseContextJson_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      parseContextJson_ = s;
      return s;
    }
  }
  /**
   * <pre>
   * Optional JSON object to configure the ParseContext for this request.
   * </pre>
   *
   * <code>string parse_context_json = 5;</code>
   * @return The bytes for parseContextJson.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getParseContextJsonBytes() {
    java.lang.Object ref = parseContextJson_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      parseContextJson_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(fetcherId_)) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 1, fetcherId_);
    }
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(fetchKey_)) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 2, fetchKey_);
    }
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(additionalFetchConfigJson_)) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 3, additionalFetchConfigJson_);
    }
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(emitterId_)) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 4, emitterId_);
    }
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(parseContextJson_)) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 5, parseContextJson_);
    }
    getUnknownFields().writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(fetcherId_)) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, fetcherId_);
    }
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(fetchKey_)) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, fetchKey_);
    }
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(additionalFetchConfigJson_)) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(3, additionalFetchConfigJson_);
    }
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(emitterId_)) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(4, emitterId_);
    }
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(parseContextJson_)) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(5, parseContextJson_);
    }
    size += getUnknownFields().getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof org.apache.tika.grpc.v2.FetchAndParseRequest)) {
      return super.equals(obj);
    }
    org.apache.tika.grpc.v2.FetchAndParseRequest other = (org.apache.tika.grpc.v2.FetchAndParseRequest) obj;

    if (!getFetcherId()
        .equals(other.getFetcherId())) return false;
    if (!getFetchKey()
        .equals(other.getFetchKey())) return false;
    if (!getAdditionalFetchConfigJson()
        .equals(other.getAdditionalFetchConfigJson())) return false;
    if (!getEmitterId()
        .equals(other.getEmitterId())) return false;
    if (!getParseContextJson()
        .equals(other.getParseContextJson())) return false;
    if (!getUnknownFields().equals(other.getUnknownFields())) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    hash = (37 * hash) + FETCHER_ID_FIELD_NUMBER;
    hash = (53 * hash) + getFetcherId().hashCode();
    hash = (37 * hash) + FETCH_KEY_FIELD_NUMBER;
    hash = (53 * hash) + getFetchKey().hashCode();
    hash = (37 * hash) + ADDITIONAL_FETCH_CONFIG_JSON_FIELD_NUMBER;
    hash = (53 * hash) + getAdditionalFetchConfigJson().hashCode();
    hash = (37 * hash) + EMITTER_ID_FIELD_NUMBER;
    hash = (53 * hash) + getEmitterId().hashCode();
    hash = (37 * hash) + PARSE_CONTEXT_JSON_FIELD_NUMBER;
    hash = (53 * hash) + getParseContextJson().hashCode();
    hash = (29 * hash) + getUnknownFields().hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static org.apache.tika.grpc.v2.FetchAndParseRequest parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static org.apache.tika.grpc.v2.FetchAndParseRequest parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static org.apache.tika.grpc.v2.FetchAndParseRequest parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static org.apache.tika.grpc.v2.FetchAndParseRequest parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static org.apache.tika.grpc.v2.FetchAndParseRequest parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static org.apache.tika.grpc.v2.FetchAndParseRequest parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static org.apache.tika.grpc.v2.FetchAndParseRequest parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static org.apache.tika.grpc.v2.FetchAndParseRequest parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  public static org.apache.tika.grpc.v2.FetchAndParseRequest parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }

  public static org.apache.tika.grpc.v2.FetchAndParseRequest parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static org.apache.tika.grpc.v2.FetchAndParseRequest parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static org.apache.tika.grpc.v2.FetchAndParseRequest parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(org.apache.tika.grpc.v2.FetchAndParseRequest prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code org.apache.tika.grpc.v2.FetchAndParseRequest}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:org.apache.tika.grpc.v2.FetchAndParseRequest)
      org.apache.tika.grpc.v2.FetchAndParseRequestOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return org.apache.tika.grpc.v2.TikaV2Proto.internal_static_org_apache_tika_grpc_v2_FetchAndParseRequest_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return org.apache.tika.grpc.v2.TikaV2Proto.internal_static_org_apache_tika_grpc_v2_FetchAndParseRequest_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              org.apache.tika.grpc.v2.FetchAndParseRequest.class, org.apache.tika.grpc.v2.FetchAndParseRequest.Builder.class);
    }

    // Construct using org.apache.tika.grpc.v2.FetchAndParseRequest.newBuilder()
    private Builder() {

    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);

    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      bitField0_ = 0;
      fetcherId_ = "";
      fetchKey_ = "";
      additionalFetchConfigJson_ = "";
      emitterId_ = "";
      parseContextJson_ = "";
      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return org.apache.tika.grpc.v2.TikaV2Proto.internal_static_org_apache_tika_grpc_v2_FetchAndParseRequest_descriptor;
    }

    @java.lang.Override
    public org.apache.tika.grpc.v2.FetchAndParseRequest getDefaultInstanceForType() {
      return org.apache.tika.grpc.v2.FetchAndParseRequest.getDefaultInstance();
    }

    @java.lang.Override
    public org.apache.tika.grpc.v2.FetchAndParseRequest build() {
      org.apache.tika.grpc.v2.FetchAndParseRequest result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public org.apache.tika.grpc.v2.FetchAndParseRequest buildPartial() {
      org.apache.tika.grpc.v2.FetchAndParseRequest result = new org.apache.tika.grpc.v2.FetchAndParseRequest(this);
      if (bitField0_ != 0) { buildPartial0(result); }
      onBuilt();
      return result;
    }

    private void buildPartial0(org.apache.tika.grpc.v2.FetchAndParseRequest result) {
      int from_bitField0_ = bitField0_;
      if (((from_bitField0_ & 0x00000001) != 0)) {
        result.fetcherId_ = fetcherId_;
      }
      if (((from_bitField0_ & 0x00000002) != 0)) {
        result.fetchKey_ = fetchKey_;
      }
      if (((from_bitField0_ & 0x00000004) != 0)) {
        result.additionalFetchConfigJson_ = additionalFetchConfigJson_;
      }
      if (((from_bitField0_ & 0x00000008) != 0)) {
        result.emitterId_ = emitterId_;
      }
      if (((from_bitField0_ & 0x00000010) != 0)) {
        result.parseContextJson_ = parseContextJson_;
      }
    }

    @java.lang.Override
    public Builder clone() {
      return super.clone();
    }
    @java.lang.Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.setField(field, value);
    }
    @java.lang.Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return super.clearField(field);
    }
    @java.lang.Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return super.clearOneof(oneof);
    }
    @java.lang.Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return super.setRepeatedField(field, index, value);
    }
    @java.lang.Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.addRepeatedField(field, value);
    }
    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof org.apache.tika.grpc.v2.FetchAndParseRequest) {
        return mergeFrom((org.apache.tika.grpc.v2.FetchAndParseRequest)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(org.apache.tika.grpc.v2.FetchAndParseRequest other) {
      if (other == org.apache.tika.grpc.v2.FetchAndParseRequest.getDefaultInstance()) return this;
      if (!other.getFetcherId().isEmpty()) {
        fetcherId_ = other.fetcherId_;
        bitField0_ |= 0x00000001;
        onChanged();
      }
      if (!other.getFetchKey().isEmpty()) {
        fetchKey_ = other.fetchKey_;
        bitField0_ |= 0x00000002;
        onChanged();
      }
      if (!other.getAdditionalFetchConfigJson().isEmpty()) {
        additionalFetchConfigJson_ = other.additionalFetchConfigJson_;
        bitField0_ |= 0x00000004;
        onChanged();
      }
      if (!other.getEmitterId().isEmpty()) {
        emitterId_ = other.emitterId_;
        bitField0_ |= 0x00000008;
        onChanged();
      }
      if (!other.getParseContextJson().isEmpty()) {
        parseContextJson_ = other.parseContextJson_;
        bitField0_ |= 0x00000010;
        onChanged();
      }
      this.mergeUnknownFields(other.getUnknownFields());
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 10: {
              fetcherId_ = input.readStringRequireUtf8();
              bitField0_ |= 0x00000001;
              break;
            } // case 10
            case 18: {
              fetchKey_ = input.readStringRequireUtf8();
              bitField0_ |= 0x00000002;
              break;
            } // case 18
            case 26: {
              additionalFetchConfigJson_ = input.readStringRequireUtf8();
              bitField0_ |= 0x00000004;
              break;
            } // case 26
            case 34: {
              emitterId_ = input.readStringRequireUtf8();
              bitField0_ |= 0x00000008;
              break;
            } // case 34
            case 42: {
              parseContextJson_ = input.readStringRequireUtf8();
              bitField0_ |= 0x00000010;
              break;
            } // case 42
            default: {
              if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                done = true; // was an endgroup tag
              }
              break;
            } // default:
          } // switch (tag)
        } // while (!done)
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.unwrapIOException();
      } finally {
        onChanged();
      } // finally
      return this;
    }
    private int bitField0_;

    private java.lang.Object fetcherId_ = "";
    /**
     * <pre>
     * ID of a fetcher previously saved through the v1 Tika service.
     * </pre>
     *
     * <code>string fetcher_id = 1;</code>
     * @return The fetcherId.
     */
    public java.lang.String getFetcherId() {
      java.lang.Object ref = fetcherId_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        fetcherId_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <pre>
     * ID of a fetcher previously saved through the v1 Tika service.
     * </pre>
     *
     * <code>string fetcher_id = 1;</code>
     * @return The bytes for fetcherId.
     */
    public com.google.protobuf.ByteString
        getFetcherIdBytes() {
      java.lang.Object ref = fetcherId_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        fetcherId_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <pre>
     * ID of a fetcher previously saved through the v1 Tika service.
     * </pre>
     *
     * <code>string fetcher_id = 1;</code>
     * @param value The fetcherId to set.
     * @return This builder for chaining.
     */
    public Builder setFetcherId(
        java.lang.String value) {
      if (value == null) { throw new NullPointerException(); }
      fetcherId_ = value;
      bitField0_ |= 0x00000001;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * ID of a fetcher previously saved through the v1 Tika service.
     * </pre>
     *
     * <code>string fetcher_id = 1;</code>
     * @return This builder for chaining.
     */
    public Builder clearFetcherId() {
      fetcherId_ = getDefaultInstance().getFetcherId();
      bitField0_ = (bitField0_ & ~0x00000001);
      onChanged();
      return this;
    }
    /**
     * <pre>
     * ID of a fetcher previously saved through the v1 Tika service.
     * </pre>
     *
     * <code>string fetcher_id = 1;</code>
     * @param value The bytes for fetcherId to set.
     * @return This builder for chaining.
     */
    public Builder setFetcherIdBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) { throw new NullPointerException(); }
      checkByteStringIsUtf8(value);
      fetcherId_ = value;
      bitField0_ |= 0x00000001;
      onChanged();
      return this;
    }

    private java.lang.Object fetchKey_ = "";
    /**
     * <code>string fetch_key = 2;</code>
     * @return The fetchKey.
     */
    public java.lang.String getFetchKey() {
      java.lang.Object ref = fetchKey_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        fetchKey_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string fetch_key = 2;</code>
     * @return The bytes for fetchKey.
     */
    public com.google.protobuf.ByteString
        getFetchKeyBytes() {
      java.lang.Object ref = fetchKey_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        fetchKey_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string fetch_key = 2;</code>
     * @param value The fetchKey to set.
     * @return This builder for chaining.
     */
    public Builder setFetchKey(
        java.lang.String value) {
      if (value == null) { throw new NullPointerException(); }
      fetchKey_ = value;
      bitField0_ |= 0x00000002;
      onChanged();
      return this;
    }
    /**
     * <code>string fetch_key = 2;</code>
     * @return This builder for chaining.
     */
    public Builder clearFetchKey() {
      fetchKey_ = getDefaultInstance().getFetchKey();
      bitField0_ = (bitField0_ & ~0x00000002);
      onChanged();
      return this;
    }
    /**
     * <code>string fetch_key = 2;</code>
     * @param value The bytes for fetchKey to set.
     * @return This builder for chaining.
     */
    public Builder setFetchKeyBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) { throw new NullPointerException(); }
      checkByteStringIsUtf8(value);
      fetchKey_ = value;
      bitField0_ |= 0x00000002;
      onChanged();
      return this;
    }

    private java.lang.Object additionalFetchConfigJson_ = "";
    /**
     * <code>string additional_fetch_config_json = 3;</code>
     * @return The additionalFetchConfigJson.
     */
    public java.lang.String getAdditionalFetchConfigJson() {
      java.lang.Object ref = additionalFetchConfigJson_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        additionalFetchConfigJson_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string additional_fetch_config_json = 3;</code>
     * @return The bytes for additionalFetchConfigJson.
     */
    public com.google.protobuf.ByteString
        getAdditionalFetchConfigJsonBytes() {
      java.lang.Object ref = additionalFetchConfigJson_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        additionalFetchConfigJson_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string additional_fetch_config_json = 3;</code>
     * @param value The additionalFetchConfigJson to set.
     * @return This builder for chaining.
     */
    public Builder setAdditionalFetchConfigJson(
        java.lang.String value) {
      if (value == null) { throw new NullPointerException(); }
      additionalFetchConfigJson_ = value;
      bitField0_ |= 0x00000004;
      onChanged();
      return this;
    }
    /**
     * <code>string additional_fetch_config_json = 3;</code>
     * @return This builder for chaining.
     */
    public Builder clearAdditionalFetchConfigJson() {
      additionalFetchConfigJson_ = getDefaultInstance().getAdditionalFetchConfigJson();
      bitField0_ = (bitField0_ & ~0x00000004);
      onChanged();
      return this;
    }
    /**
     * <code>string additional_fetch_config_json = 3;</code>
     * @param value The bytes for additionalFetchConfigJson to set.
     * @return This builder for chaining.
     */
    public Builder setAdditionalFetchConfigJsonBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) { throw new NullPointerException(); }
      checkByteStringIsUtf8(value);
      additionalFetchConfigJson_ = value;
      bitField0_ |= 0x00000004;
      onChanged();
      return this;
    }

    private java.lang.Object emitterId_ = "";
    /**
     * <code>string emitter_id = 4;</code>
     * @return The emitterId.
     */
    public java.lang.String getEmitterId() {
      java.lang.Object ref = emitterId_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        emitterId_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string emitter_id = 4;</code>
     * @return The bytes for emitterId.
     */
    public com.google.protobuf.ByteString
        getEmitterIdBytes() {
      java.lang.Object ref = emitterId_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        emitterId_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string emitter_id = 4;</code>
     * @param value The emitterId to set.
     * @return This builder for chaining.
     */
    public Builder setEmitterId(
        java.lang.String value) {
      if (value == null) { throw new NullPointerException(); }
      emitterId_ = value;
      bitField0_ |= 0x00000008;
      onChanged();
      return this;
    }
    /**
     * <code>string emitter_id = 4;</code>
     * @return This builder for chaining.
     */
    public Builder clearEmitterId() {
      emitterId_ = getDefaultInstance().getEmitterId();
      bitField0_ = (bitField0_ & ~0x00000008);
      onChanged();
      return this;
    }
    /**
     * <code>string emitter_id = 4;</code>
     * @param value The bytes for emitterId to set.
     * @return This builder for chaining.
     */
    public Builder setEmitterIdBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) { throw new NullPointerException(); }
      checkByteStringIsUtf8(value);
      emitterId_ = value;
      bitField0_ |= 0x00000008;
      onChanged();
      return this;
    }

    private java.lang.Object parseContextJson_ = "";
    /**
     * <pre>
     * Optional JSON object to configure the ParseContext for this request.
     * </pre>
     *
     * <code>string parse_context_json = 5;</code>
     * @return The parseContextJson.
     */
    public java.lang.String getParseContextJson() {
      java.lang.Object ref = parseContextJson_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        parseContextJson_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <pre>
     * Optional JSON object to configure the ParseContext for this request.
     * </pre>
     *
     * <code>string parse_context_json = 5;</code>
     * @return The bytes for parseContextJson.
     */
    public com.google.protobuf.ByteString
        getParseContextJsonBytes() {
      java.lang.Object ref = parseContextJson_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        parseContextJson_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <pre>
     * Optional JSON object to configure the ParseContext for this request.
     * </pre>
     *
     * <code>string parse_context_json = 5;</code>
     * @param value The parseContextJson to set.
     * @return This builder for chaining.
     */
    public Builder setParseContextJson(
        java.lang.String value) {
      if (value == null) { throw new NullPointerException(); }
      parseContextJson_ = value;
      bitField0_ |= 0x00000010;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * Optional JSON object to configure the ParseContext for this request.
     * </pre>
     *
     * <code>string parse_context_json = 5;</code>
     * @return This builder for chaining.
     */
    public Builder clearParseContextJson() {
      parseContextJson_ = getDefaultInstance().getParseContextJson();
      bitField0_ = (bitField0_ & ~0x00000010);
      onChanged();
      return this;
    }
    /**
     * <pre>
     * Optional JSON object to configure the ParseContext for this request.
     * </pre>
     *
     * <code>string parse_context_json = 5;</code>
     * @param value The bytes for parseContextJson to set.
     * @return This builder for chaining.
     */
    public Builder setParseContextJsonBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) { throw new NullPointerException(); }
      checkByteStringIsUtf8(value);
      parseContextJson_ = value;
      bitField0_ |= 0x00000010;
      onChanged();
      return this;
    }
    @java.lang.Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFields(unknownFields);
    }

    @java.lang.Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:org.apache.tika.grpc.v2.FetchAndParseRequest)
  }

  // @@protoc_insertion_point(class_scope:org.apache.tika.grpc.v2.FetchAndParseRequest)
  private static final org.apache.tika.grpc.v2.FetchAndParseRequest DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new org.apache.tika.grpc.v2.FetchAndParseRequest();
  }

  public static org.apache.tika.grpc.v2.FetchAndParseRequest getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<FetchAndParseRequest>
      PARSER = new com.google.protobuf.AbstractParser<FetchAndParseRequest>() {
    @java.lang.Override
    public FetchAndParseRequest parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      Builder builder = newBuilder();
      try {
        builder.mergeFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(builder.buildPartial());
      } catch (com.google.protobuf.UninitializedMessageException e) {
        throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(e)
            .setUnfinishedMessage(builder.buildPartial());
      }
      return builder.buildPartial();
    }
  };

  public static com.google.protobuf.Parser<FetchAndParseRequest> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<FetchAndParseRequest> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public org.apache.tika.grpc.v2.FetchAndParseRequest getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

