// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: org/apache/tika/grpc/v2/tika_v2.proto

// Protobuf Java Version: 3.25.8
package org.apache.tika.grpc.v2;

public interface FetchAndParseReplyOrBuilder extends
    // @@protoc_insertion_point(interface_extends:org.apache.tika.grpc.v2.FetchAndParseReply)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string fetch_key = 1;</code>
   * @return The fetchKey.
   */
  java.lang.String getFetchKey();
  /**
   * <code>string fetch_key = 1;</code>
   * @return The bytes for fetchKey.
   */
  com.google.protobuf.ByteString
      getFetchKeyBytes();

  /**
   * <code>.org.apache.tika.grpc.v2.Document document = 2;</code>
   * @return Whether the document field is set.
   */
  boolean hasDocument();
  /**
   * <code>.org.apache.tika.grpc.v2.Document document = 2;</code>
   * @return The document.
   */
  org.apache.tika.grpc.v2.Document getDocument();
  /**
   * <code>.org.apache.tika.grpc.v2.Document document = 2;</code>
   */
  org.apache.tika.grpc.v2.DocumentOrBuilder getDocumentOrBuilder();
}
