// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: org/apache/tika/grpc/v2/tika_v2.proto

// Protobuf Java Version: 3.25.8
package org.apache.tika.grpc.v2;

public interface FetchAndParseRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:org.apache.tika.grpc.v2.FetchAndParseRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <pre>
   * ID of a fetcher previously saved through the v1 Tika service.
   * </pre>
   *
   * <code>string fetcher_id = 1;</code>
   * @return The fetcherId.
   */
  java.lang.String getFetcherId();
  /**
   * <pre>
   * ID of a fetcher previously saved through the v1 Tika service.
   * </pre>
   *
   * <code>string fetcher_id = 1;</code>
   * @return The bytes for fetcherId.
   */
  com.google.protobuf.ByteString
      getFetcherIdBytes();

  /**
   * <code>string fetch_key = 2;</code>
   * @return The fetchKey.
   */
  java.lang.String getFetchKey();
  /**
   * <code>string fetch_key = 2;</code>
   * @return The bytes for fetchKey.
   */
  com.google.protobuf.ByteString
      getFetchKeyBytes();

  /**
   * <code>string additional_fetch_config_json = 3;</code>
   * @return The additionalFetchConfigJson.
   */
  java.lang.String getAdditionalFetchConfigJson();
  /**
   * <code>string additional_fetch_config_json = 3;</code>
   * @return The bytes for additionalFetchConfigJson.
   */
  com.google.protobuf.ByteString
      getAdditionalFetchConfigJsonBytes();

  /**
   * <code>string emitter_id = 4;</code>
   * @return The emitterId.
   */
  java.lang.String getEmitterId();
  /**
   * <code>string emitter_id = 4;</code>
   * @return The bytes for emitterId.
   */
  com.google.protobuf.ByteString
      getEmitterIdBytes();

  /**
   * <pre>
   * Optional JSON object to configure the ParseContext for this request.
   * </pre>
   *
   * <code>string parse_context_json = 5;</code>
   * @return The parseContextJson.
   */
  java.lang.String getParseContextJson();
  /**
   * <pre>
   * Optional JSON object to configure the ParseContext for this request.
   * </pre>
   *
   * <code>string parse_context_json = 5;</code>
   * @return The bytes for parseContextJson.
   */
  com.google.protobuf.ByteString
      getParseContextJsonBytes();
}
