// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: org/apache/tika/grpc/v2/document.proto

// Protobuf Java Version: 3.25.8
package org.apache.tika.grpc.v2;

public interface MetadataFieldOrBuilder extends
    // @@protoc_insertion_point(interface_extends:org.apache.tika.grpc.v2.MetadataField)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string key = 1;</code>
   * @return The key.
   */
  java.lang.String getKey();
  /**
   * <code>string key = 1;</code>
   * @return The bytes for key.
   */
  com.google.protobuf.ByteString
      getKeyBytes();

  /**
   * <code>.org.apache.tika.grpc.v2.MetadataValue value = 2;</code>
   * @return Whether the value field is set.
   */
  boolean hasValue();
  /**
   * <code>.org.apache.tika.grpc.v2.MetadataValue value = 2;</code>
   * @return The value.
   */
  org.apache.tika.grpc.v2.MetadataValue getValue();
  /**
   * <code>.org.apache.tika.grpc.v2.MetadataValue value = 2;</code>
   */
  org.apache.tika.grpc.v2.MetadataValueOrBuilder getValueOrBuilder();
}
