// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: org/apache/tika/grpc/v2/document.proto

// Protobuf Java Version: 3.25.8
package org.apache.tika.grpc.v2;

public interface NumberValuesOrBuilder extends
    // @@protoc_insertion_point(interface_extends:org.apache.tika.grpc.v2.NumberValues)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>repeated double values = 1;</code>
   * @return A list containing the values.
   */
  java.util.List<java.lang.Double> getValuesList();
  /**
   * <code>repeated double values = 1;</code>
   * @return The count of values.
   */
  int getValuesCount();
  /**
   * <code>repeated double values = 1;</code>
   * @param index The index of the element to return.
   * @return The values at the given index.
   */
  double getValues(int index);
}
