// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: org/apache/tika/grpc/v2/tika_v2.proto

// Protobuf Java Version: 3.25.8
package org.apache.tika.grpc.v2;

/**
 * Protobuf type {@code org.apache.tika.grpc.v2.ParseBytesReply}
 */
public final class ParseBytesReply extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:org.apache.tika.grpc.v2.ParseBytesReply)
    ParseBytesReplyOrBuilder {
private static final long serialVersionUID = 0L;
  // Use ParseBytesReply.newBuilder() to construct.
  private ParseBytesReply(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private ParseBytesReply() {
    correlationId_ = "";
  }

  @java.lang.Override
  @SuppressWarnings({"unused"})
  protected java.lang.Object newInstance(
      UnusedPrivateParameter unused) {
    return new ParseBytesReply();
  }

  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return org.apache.tika.grpc.v2.TikaV2Proto.internal_static_org_apache_tika_grpc_v2_ParseBytesReply_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return org.apache.tika.grpc.v2.TikaV2Proto.internal_static_org_apache_tika_grpc_v2_ParseBytesReply_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            org.apache.tika.grpc.v2.ParseBytesReply.class, org.apache.tika.grpc.v2.ParseBytesReply.Builder.class);
  }

  private int bitField0_;
  public static final int CORRELATION_ID_FIELD_NUMBER = 1;
  @SuppressWarnings("serial")
  private volatile java.lang.Object correlationId_ = "";
  /**
   * <code>string correlation_id = 1;</code>
   * @return The correlationId.
   */
  @java.lang.Override
  public java.lang.String getCorrelationId() {
    java.lang.Object ref = correlationId_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      correlationId_ = s;
      return s;
    }
  }
  /**
   * <code>string correlation_id = 1;</code>
   * @return The bytes for correlationId.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getCorrelationIdBytes() {
    java.lang.Object ref = correlationId_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      correlationId_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int DOCUMENT_FIELD_NUMBER = 2;
  private org.apache.tika.grpc.v2.Document document_;
  /**
   * <code>.org.apache.tika.grpc.v2.Document document = 2;</code>
   * @return Whether the document field is set.
   */
  @java.lang.Override
  public boolean hasDocument() {
    return ((bitField0_ & 0x00000001) != 0);
  }
  /**
   * <code>.org.apache.tika.grpc.v2.Document document = 2;</code>
   * @return The document.
   */
  @java.lang.Override
  public org.apache.tika.grpc.v2.Document getDocument() {
    return document_ == null ? org.apache.tika.grpc.v2.Document.getDefaultInstance() : document_;
  }
  /**
   * <code>.org.apache.tika.grpc.v2.Document document = 2;</code>
   */
  @java.lang.Override
  public org.apache.tika.grpc.v2.DocumentOrBuilder getDocumentOrBuilder() {
    return document_ == null ? org.apache.tika.grpc.v2.Document.getDefaultInstance() : document_;
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(correlationId_)) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 1, correlationId_);
    }
    if (((bitField0_ & 0x00000001) != 0)) {
      output.writeMessage(2, getDocument());
    }
    getUnknownFields().writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(correlationId_)) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, correlationId_);
    }
    if (((bitField0_ & 0x00000001) != 0)) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(2, getDocument());
    }
    size += getUnknownFields().getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof org.apache.tika.grpc.v2.ParseBytesReply)) {
      return super.equals(obj);
    }
    org.apache.tika.grpc.v2.ParseBytesReply other = (org.apache.tika.grpc.v2.ParseBytesReply) obj;

    if (!getCorrelationId()
        .equals(other.getCorrelationId())) return false;
    if (hasDocument() != other.hasDocument()) return false;
    if (hasDocument()) {
      if (!getDocument()
          .equals(other.getDocument())) return false;
    }
    if (!getUnknownFields().equals(other.getUnknownFields())) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    hash = (37 * hash) + CORRELATION_ID_FIELD_NUMBER;
    hash = (53 * hash) + getCorrelationId().hashCode();
    if (hasDocument()) {
      hash = (37 * hash) + DOCUMENT_FIELD_NUMBER;
      hash = (53 * hash) + getDocument().hashCode();
    }
    hash = (29 * hash) + getUnknownFields().hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static org.apache.tika.grpc.v2.ParseBytesReply parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static org.apache.tika.grpc.v2.ParseBytesReply parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static org.apache.tika.grpc.v2.ParseBytesReply parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static org.apache.tika.grpc.v2.ParseBytesReply parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static org.apache.tika.grpc.v2.ParseBytesReply parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static org.apache.tika.grpc.v2.ParseBytesReply parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static org.apache.tika.grpc.v2.ParseBytesReply parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static org.apache.tika.grpc.v2.ParseBytesReply parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  public static org.apache.tika.grpc.v2.ParseBytesReply parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }

  public static org.apache.tika.grpc.v2.ParseBytesReply parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static org.apache.tika.grpc.v2.ParseBytesReply parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static org.apache.tika.grpc.v2.ParseBytesReply parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(org.apache.tika.grpc.v2.ParseBytesReply prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code org.apache.tika.grpc.v2.ParseBytesReply}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:org.apache.tika.grpc.v2.ParseBytesReply)
      org.apache.tika.grpc.v2.ParseBytesReplyOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return org.apache.tika.grpc.v2.TikaV2Proto.internal_static_org_apache_tika_grpc_v2_ParseBytesReply_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return org.apache.tika.grpc.v2.TikaV2Proto.internal_static_org_apache_tika_grpc_v2_ParseBytesReply_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              org.apache.tika.grpc.v2.ParseBytesReply.class, org.apache.tika.grpc.v2.ParseBytesReply.Builder.class);
    }

    // Construct using org.apache.tika.grpc.v2.ParseBytesReply.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
        getDocumentFieldBuilder();
      }
    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      bitField0_ = 0;
      correlationId_ = "";
      document_ = null;
      if (documentBuilder_ != null) {
        documentBuilder_.dispose();
        documentBuilder_ = null;
      }
      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return org.apache.tika.grpc.v2.TikaV2Proto.internal_static_org_apache_tika_grpc_v2_ParseBytesReply_descriptor;
    }

    @java.lang.Override
    public org.apache.tika.grpc.v2.ParseBytesReply getDefaultInstanceForType() {
      return org.apache.tika.grpc.v2.ParseBytesReply.getDefaultInstance();
    }

    @java.lang.Override
    public org.apache.tika.grpc.v2.ParseBytesReply build() {
      org.apache.tika.grpc.v2.ParseBytesReply result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public org.apache.tika.grpc.v2.ParseBytesReply buildPartial() {
      org.apache.tika.grpc.v2.ParseBytesReply result = new org.apache.tika.grpc.v2.ParseBytesReply(this);
      if (bitField0_ != 0) { buildPartial0(result); }
      onBuilt();
      return result;
    }

    private void buildPartial0(org.apache.tika.grpc.v2.ParseBytesReply result) {
      int from_bitField0_ = bitField0_;
      if (((from_bitField0_ & 0x00000001) != 0)) {
        result.correlationId_ = correlationId_;
      }
      int to_bitField0_ = 0;
      if (((from_bitField0_ & 0x00000002) != 0)) {
        result.document_ = documentBuilder_ == null
            ? document_
            : documentBuilder_.build();
        to_bitField0_ |= 0x00000001;
      }
      result.bitField0_ |= to_bitField0_;
    }

    @java.lang.Override
    public Builder clone() {
      return super.clone();
    }
    @java.lang.Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.setField(field, value);
    }
    @java.lang.Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return super.clearField(field);
    }
    @java.lang.Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return super.clearOneof(oneof);
    }
    @java.lang.Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return super.setRepeatedField(field, index, value);
    }
    @java.lang.Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.addRepeatedField(field, value);
    }
    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof org.apache.tika.grpc.v2.ParseBytesReply) {
        return mergeFrom((org.apache.tika.grpc.v2.ParseBytesReply)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(org.apache.tika.grpc.v2.ParseBytesReply other) {
      if (other == org.apache.tika.grpc.v2.ParseBytesReply.getDefaultInstance()) return this;
      if (!other.getCorrelationId().isEmpty()) {
        correlationId_ = other.correlationId_;
        bitField0_ |= 0x00000001;
        onChanged();
      }
      if (other.hasDocument()) {
        mergeDocument(other.getDocument());
      }
      this.mergeUnknownFields(other.getUnknownFields());
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 10: {
              correlationId_ = input.readStringRequireUtf8();
              bitField0_ |= 0x00000001;
              break;
            } // case 10
            case 18: {
              input.readMessage(
                  getDocumentFieldBuilder().getBuilder(),
                  extensionRegistry);
              bitField0_ |= 0x00000002;
              break;
            } // case 18
            default: {
              if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                done = true; // was an endgroup tag
              }
              break;
            } // default:
          } // switch (tag)
        } // while (!done)
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.unwrapIOException();
      } finally {
        onChanged();
      } // finally
      return this;
    }
    private int bitField0_;

    private java.lang.Object correlationId_ = "";
    /**
     * <code>string correlation_id = 1;</code>
     * @return The correlationId.
     */
    public java.lang.String getCorrelationId() {
      java.lang.Object ref = correlationId_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        correlationId_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string correlation_id = 1;</code>
     * @return The bytes for correlationId.
     */
    public com.google.protobuf.ByteString
        getCorrelationIdBytes() {
      java.lang.Object ref = correlationId_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        correlationId_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string correlation_id = 1;</code>
     * @param value The correlationId to set.
     * @return This builder for chaining.
     */
    public Builder setCorrelationId(
        java.lang.String value) {
      if (value == null) { throw new NullPointerException(); }
      correlationId_ = value;
      bitField0_ |= 0x00000001;
      onChanged();
      return this;
    }
    /**
     * <code>string correlation_id = 1;</code>
     * @return This builder for chaining.
     */
    public Builder clearCorrelationId() {
      correlationId_ = getDefaultInstance().getCorrelationId();
      bitField0_ = (bitField0_ & ~0x00000001);
      onChanged();
      return this;
    }
    /**
     * <code>string correlation_id = 1;</code>
     * @param value The bytes for correlationId to set.
     * @return This builder for chaining.
     */
    public Builder setCorrelationIdBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) { throw new NullPointerException(); }
      checkByteStringIsUtf8(value);
      correlationId_ = value;
      bitField0_ |= 0x00000001;
      onChanged();
      return this;
    }

    private org.apache.tika.grpc.v2.Document document_;
    private com.google.protobuf.SingleFieldBuilderV3<
        org.apache.tika.grpc.v2.Document, org.apache.tika.grpc.v2.Document.Builder, org.apache.tika.grpc.v2.DocumentOrBuilder> documentBuilder_;
    /**
     * <code>.org.apache.tika.grpc.v2.Document document = 2;</code>
     * @return Whether the document field is set.
     */
    public boolean hasDocument() {
      return ((bitField0_ & 0x00000002) != 0);
    }
    /**
     * <code>.org.apache.tika.grpc.v2.Document document = 2;</code>
     * @return The document.
     */
    public org.apache.tika.grpc.v2.Document getDocument() {
      if (documentBuilder_ == null) {
        return document_ == null ? org.apache.tika.grpc.v2.Document.getDefaultInstance() : document_;
      } else {
        return documentBuilder_.getMessage();
      }
    }
    /**
     * <code>.org.apache.tika.grpc.v2.Document document = 2;</code>
     */
    public Builder setDocument(org.apache.tika.grpc.v2.Document value) {
      if (documentBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        document_ = value;
      } else {
        documentBuilder_.setMessage(value);
      }
      bitField0_ |= 0x00000002;
      onChanged();
      return this;
    }
    /**
     * <code>.org.apache.tika.grpc.v2.Document document = 2;</code>
     */
    public Builder setDocument(
        org.apache.tika.grpc.v2.Document.Builder builderForValue) {
      if (documentBuilder_ == null) {
        document_ = builderForValue.build();
      } else {
        documentBuilder_.setMessage(builderForValue.build());
      }
      bitField0_ |= 0x00000002;
      onChanged();
      return this;
    }
    /**
     * <code>.org.apache.tika.grpc.v2.Document document = 2;</code>
     */
    public Builder mergeDocument(org.apache.tika.grpc.v2.Document value) {
      if (documentBuilder_ == null) {
        if (((bitField0_ & 0x00000002) != 0) &&
          document_ != null &&
          document_ != org.apache.tika.grpc.v2.Document.getDefaultInstance()) {
          getDocumentBuilder().mergeFrom(value);
        } else {
          document_ = value;
        }
      } else {
        documentBuilder_.mergeFrom(value);
      }
      if (document_ != null) {
        bitField0_ |= 0x00000002;
        onChanged();
      }
      return this;
    }
    /**
     * <code>.org.apache.tika.grpc.v2.Document document = 2;</code>
     */
    public Builder clearDocument() {
      bitField0_ = (bitField0_ & ~0x00000002);
      document_ = null;
      if (documentBuilder_ != null) {
        documentBuilder_.dispose();
        documentBuilder_ = null;
      }
      onChanged();
      return this;
    }
    /**
     * <code>.org.apache.tika.grpc.v2.Document document = 2;</code>
     */
    public org.apache.tika.grpc.v2.Document.Builder getDocumentBuilder() {
      bitField0_ |= 0x00000002;
      onChanged();
      return getDocumentFieldBuilder().getBuilder();
    }
    /**
     * <code>.org.apache.tika.grpc.v2.Document document = 2;</code>
     */
    public org.apache.tika.grpc.v2.DocumentOrBuilder getDocumentOrBuilder() {
      if (documentBuilder_ != null) {
        return documentBuilder_.getMessageOrBuilder();
      } else {
        return document_ == null ?
            org.apache.tika.grpc.v2.Document.getDefaultInstance() : document_;
      }
    }
    /**
     * <code>.org.apache.tika.grpc.v2.Document document = 2;</code>
     */
    private com.google.protobuf.SingleFieldBuilderV3<
        org.apache.tika.grpc.v2.Document, org.apache.tika.grpc.v2.Document.Builder, org.apache.tika.grpc.v2.DocumentOrBuilder> 
        getDocumentFieldBuilder() {
      if (documentBuilder_ == null) {
        documentBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
            org.apache.tika.grpc.v2.Document, org.apache.tika.grpc.v2.Document.Builder, org.apache.tika.grpc.v2.DocumentOrBuilder>(
                getDocument(),
                getParentForChildren(),
                isClean());
        document_ = null;
      }
      return documentBuilder_;
    }
    @java.lang.Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFields(unknownFields);
    }

    @java.lang.Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:org.apache.tika.grpc.v2.ParseBytesReply)
  }

  // @@protoc_insertion_point(class_scope:org.apache.tika.grpc.v2.ParseBytesReply)
  private static final org.apache.tika.grpc.v2.ParseBytesReply DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new org.apache.tika.grpc.v2.ParseBytesReply();
  }

  public static org.apache.tika.grpc.v2.ParseBytesReply getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<ParseBytesReply>
      PARSER = new com.google.protobuf.AbstractParser<ParseBytesReply>() {
    @java.lang.Override
    public ParseBytesReply parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      Builder builder = newBuilder();
      try {
        builder.mergeFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(builder.buildPartial());
      } catch (com.google.protobuf.UninitializedMessageException e) {
        throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(e)
            .setUnfinishedMessage(builder.buildPartial());
      }
      return builder.buildPartial();
    }
  };

  public static com.google.protobuf.Parser<ParseBytesReply> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<ParseBytesReply> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public org.apache.tika.grpc.v2.ParseBytesReply getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

