// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: org/apache/tika/grpc/v2/document.proto

// Protobuf Java Version: 3.25.8
package org.apache.tika.grpc.v2;

public interface SourceOriginOrBuilder extends
    // @@protoc_insertion_point(interface_extends:org.apache.tika.grpc.v2.SourceOrigin)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string filename = 1;</code>
   * @return The filename.
   */
  java.lang.String getFilename();
  /**
   * <code>string filename = 1;</code>
   * @return The bytes for filename.
   */
  com.google.protobuf.ByteString
      getFilenameBytes();

  /**
   * <code>int64 byte_size = 2;</code>
   * @return The byteSize.
   */
  long getByteSize();

  /**
   * <code>string parser = 3;</code>
   * @return The parser.
   */
  java.lang.String getParser();
  /**
   * <code>string parser = 3;</code>
   * @return The bytes for parser.
   */
  com.google.protobuf.ByteString
      getParserBytes();

  /**
   * <pre>
   * Hex-encoded SHA-256 of the source bytes, taken from the digest the parse pipeline
   * recorded (the X-TIKA:digest:SHA256 metadata value). Empty when the pipeline has no
   * digester configured. Downstream consumers use it to tie derived artifacts
   * (annotations, index entries) back to the exact bytes that were parsed.
   * </pre>
   *
   * <code>string sha256 = 4;</code>
   * @return The sha256.
   */
  java.lang.String getSha256();
  /**
   * <pre>
   * Hex-encoded SHA-256 of the source bytes, taken from the digest the parse pipeline
   * recorded (the X-TIKA:digest:SHA256 metadata value). Empty when the pipeline has no
   * digester configured. Downstream consumers use it to tie derived artifacts
   * (annotations, index entries) back to the exact bytes that were parsed.
   * </pre>
   *
   * <code>string sha256 = 4;</code>
   * @return The bytes for sha256.
   */
  com.google.protobuf.ByteString
      getSha256Bytes();

  /**
   * <pre>
   * Caller-supplied provenance for parse-only entrypoints (e.g. ParseBytes). These
   * are never dereferenced by the service; they describe the representation the
   * caller already captured.
   * </pre>
   *
   * <code>string source_uri = 5;</code>
   * @return The sourceUri.
   */
  java.lang.String getSourceUri();
  /**
   * <pre>
   * Caller-supplied provenance for parse-only entrypoints (e.g. ParseBytes). These
   * are never dereferenced by the service; they describe the representation the
   * caller already captured.
   * </pre>
   *
   * <code>string source_uri = 5;</code>
   * @return The bytes for sourceUri.
   */
  com.google.protobuf.ByteString
      getSourceUriBytes();

  /**
   * <code>string effective_uri = 6;</code>
   * @return The effectiveUri.
   */
  java.lang.String getEffectiveUri();
  /**
   * <code>string effective_uri = 6;</code>
   * @return The bytes for effectiveUri.
   */
  com.google.protobuf.ByteString
      getEffectiveUriBytes();

  /**
   * <code>string base_uri = 7;</code>
   * @return The baseUri.
   */
  java.lang.String getBaseUri();
  /**
   * <code>string base_uri = 7;</code>
   * @return The bytes for baseUri.
   */
  com.google.protobuf.ByteString
      getBaseUriBytes();

  /**
   * <code>bool truncated = 8;</code>
   * @return The truncated.
   */
  boolean getTruncated();
}
