// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: org/apache/tika/grpc/v2/document.proto

// Protobuf Java Version: 3.25.8
package org.apache.tika.grpc.v2;

public interface TimestampValuesOrBuilder extends
    // @@protoc_insertion_point(interface_extends:org.apache.tika.grpc.v2.TimestampValues)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>repeated .google.protobuf.Timestamp values = 1;</code>
   */
  java.util.List<com.google.protobuf.Timestamp> 
      getValuesList();
  /**
   * <code>repeated .google.protobuf.Timestamp values = 1;</code>
   */
  com.google.protobuf.Timestamp getValues(int index);
  /**
   * <code>repeated .google.protobuf.Timestamp values = 1;</code>
   */
  int getValuesCount();
  /**
   * <code>repeated .google.protobuf.Timestamp values = 1;</code>
   */
  java.util.List<? extends com.google.protobuf.TimestampOrBuilder> 
      getValuesOrBuilderList();
  /**
   * <code>repeated .google.protobuf.Timestamp values = 1;</code>
   */
  com.google.protobuf.TimestampOrBuilder getValuesOrBuilder(
      int index);
}
